#!/bin/bash

# Get the microphone status using pactl
MUTED=$(pactl get-source-mute @DEFAULT_SOURCE@ | grep -o "yes")

if [ "$MUTED" == "yes" ]; then
    echo " Muted"  # Adjust the icon to your preference
else
    echo " On"
fi
