#!/bin/bash

# Toggle mic mute
amixer sset Capture toggle

# Check mic status (muted or unmuted)
mic_status=$(amixer get Capture | grep '\[on\]' > /dev/null && echo "Unmuted" || echo "Muted")

# Send notification using Dunst
if [ "$mic_status" == "Muted" ]; then
    dunstify -i microphone-sensitivity-muted -t 1000 -r 2594 -u normal "Microphone" "Muted"
else
    dunstify -i microphone-sensitivity-high -t 1000 -r 2594 -u normal "Microphone" "Unmuted"
fi
