#!/bin/bash

# Get the command argument (pause, next, prev)
action=$1
player=$(playerctl -l | grep spotify | head -n 1 2>/dev/null)  # Get Spotify player only

if [[ $player == "spotify" ]]; then
    case $action in
        pause)
            playerctl -p "$player" play-pause
            ;;
        next)
            playerctl -p "$player" next
            ;;
        prev)
            playerctl -p "$player" previous
            ;;
        *)
            echo "Invalid action. Use 'pause', 'next', or 'prev'."
            ;;
    esac
else
    echo "Spotify is not running."
fi
