#!/bin/bash

# Get the player name, metadata, and status
player=$(playerctl -l | grep spotify | head -n 1 2>/dev/null)  # Get Spotify player only
metadata=$(playerctl -p "$player" metadata --format "{{ title }}" 2>/dev/null)
status=$(playerctl -p "$player" status 2>/dev/null)

if [[ $player == "spotify" && ($status == "Playing" || $status == "Paused") ]]; then
    echo "$metadata"  # Show player name and metadata
else
    echo "Spotify not running"
fi
