#!/bin/bash

# Get the player name, metadata, and status
player=$(playerctl -l | grep spotify | head -n 1 2>/dev/null)  # Get Spotify player only
status=$(playerctl -p "$player" status 2>/dev/null)

if [[ $status == "Playing" ]]; then
    echo ""  # Show player name and metadata
else
    echo ""
fi
