#!/bin/sh

get_icon() {
    case $1 in
        # Icons and captions for Nerd Fonts
        01d) icon=" Clear";;       # Clear sky (day)
        01n) icon=" Clear";;       # Clear sky (night)
        02d) icon=" Partly Cloudy";; # Few clouds (day)
        02n) icon=" Partly Cloudy";; # Few clouds (night)
        03*) icon=" Scattered Clouds";; # Scattered clouds
        04*) icon=" Overcast";;    # Broken clouds
        09d) icon=" Showers";;     # Shower rain (day)
        09n) icon=" Showers";;     # Shower rain (night)
        10d) icon=" Rain";;        # Rain (day)
        10n) icon=" Rain";;        # Rain (night)
        11d) icon=" Thunderstorm";; # Thunderstorm (day)
        11n) icon=" Thunderstorm";; # Thunderstorm (night)
        13d) icon=" Snow";;        # Snow (day)
        13n) icon=" Snow";;        # Snow (night)
        50d) icon=" Mist";;        # Mist or fog (day)
        50n) icon=" Mist";;        # Mist or fog (night)
        *)    icon=" Unknown";;    # Default/Unknown
    esac

    echo $icon
}


get_duration() {

    osname=$(uname -s)

    case $osname in
        *BSD) date -r "$1" -u +%H:%M;;
        *) date --date="@$1" -u +%H:%M;;
    esac

}

KEY="open_weather_api_key"
CITY="open_weather_city_id"
UNITS="metric"
SYMBOL="°"

API="https://api.openweathermap.org/data/2.5"

if [ -n "$CITY" ]; then
    if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
        CITY_PARAM="id=$CITY"
    else
        CITY_PARAM="q=$CITY"
    fi

    current=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
    forecast=$(curl -sf "$API/forecast?appid=$KEY&$CITY_PARAM&units=$UNITS&cnt=1")
else
    location=$(curl -sf "https://location.services.mozilla.com/v1/geolocate?key=geoclue")

    if [ -n "$location" ]; then
        location_lat="$(echo "$location" | jq '.location.lat')"
        location_lon="$(echo "$location" | jq '.location.lng')"

        current=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
        forecast=$(curl -sf "$API/forecast?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS&cnt=1")
    fi
fi

if [ -n "$current" ] && [ -n "$forecast" ]; then
    current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
    current_icon=$(echo "$current" | jq -r ".weather[0].icon")

    forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
    forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[0].icon")


    if [ "$current_temp" -gt "$forecast_temp" ]; then
        trend="󰔳 Cooling"
    elif [ "$forecast_temp" -gt "$current_temp" ]; then
        trend="󰔴 Stable"
    else
        trend="󰔵 Warming"
    fi


    sun_rise=$(echo "$current" | jq ".sys.sunrise")
    sun_set=$(echo "$current" | jq ".sys.sunset")
    now=$(date +%s)

    if [ "$sun_rise" -gt "$now" ]; then
        daytime="󰖚 Night $(get_duration "$((sun_rise-now))")"
    elif [ "$sun_set" -gt "$now" ]; then
        daytime=" Day $(get_duration "$((sun_set-now))")"
    else
        daytime="󰖚 Night $(get_duration "$((sun_rise-now))")"
    fi

    echo "$(get_icon "$current_icon") $current_temp$SYMBOL $trend $daytime"
fi
